<!--
// Name: Enrollment Wizard
// Committer: andrew@zpaper.com
// Update: updating static resource
-->
<script>
//--- RULE JSON REPRESENTATION ---
var ruleJson = {"type":"rool","updated":"2021-02-25 19:02:37","active":true,"button":"Enrollment Wizard","name":"Enrollment Wizard","conditions":{"logic":"and","arguments":[{"name":"doc.X(\"X_buttonAction\")","value":"Wizard","operation":"contains"}]},"consequence":{"doit":"Ly9hZGRpbmcgbGluZXMgZm9yIGRlZmF1bHQ="},"ordinal":13}

//--- RULE JSON REPRESENTATION - END ---

//--- RULE CONSEQUENCE CODE ---
//adding lines for default
//--- RULE CONSEQUENCE CODE - END ---

//--- RULE VALIDATION CODE ---
bGV0IHJlZGlyZWN0UGF0aCA9ICJodHRwczovL3Rha2VkYXBhdGllbnRzZXJ2aWNlcy0tdGtkZXYyLS1jLnZpc3VhbGZvcmNlLmNvbS9hcGV4L1RLX0RhdGFFbnRyeVBhZ2UiOwpsZXQgcGFyYW1zID0gYHNjcm9sbGJhcnM9bm8scmVzaXphYmxlPW5vLHN0YXR1cz1ubyxsb2NhdGlvbj1ubyx0b29sYmFyPW5vLG1lbnViYXI9bm8sd2lkdGg9MTAwMCxoZWlnaHQ9ODAwLGxlZnQ9MTAwLHRvcD0xMDBgOwp3aW5kb3cub3BlbihyZWRpcmVjdFBhdGgsICdFbnJvbGxtZW50IFdpemFyZCcsIHBhcmFtcyk7CnJldHVybiB0cnVlOw==
//--- RULE VALIDATION CODE - END ---

</script>
