<!--
// Name: Malala Test
// Committer: Marty Harvey:marty.harvey@zpaper.com
// Update: Isabela (not Marty) added the Malala rule. 
-->
<script>
//--- RULE JSON REPRESENTATION ---
var ruleJson = {"type":"rool","updated":"2020-02-20 20:33:33","active":true,"button":"","name":"Malala Test","conditions":{"logic":"and","arguments":[{"name":"doc.X(\"X_docType\")","value":"GS01","operation":"equals"}]},"consequence":{"doit":""},"ordinal":9}

//--- RULE JSON REPRESENTATION - END ---

//--- RULE CONSEQUENCE CODE ---

//--- RULE CONSEQUENCE CODE - END ---

//--- RULE VALIDATION CODE ---
//--- RULE VALIDATION CODE - END ---

</script>
